### ISSUE TITLE
Create architecture diagram for Scribe

### ISSUE THREAD

**Issue by wkyoshida** [scribe-org/Organization#8]
This issue is for creating an architecture diagram for all of Scribe. Goal is to demonstrate how the different components fit together and interact (or will as planned) - including the Scribe apps, service, data processes, and sources of data (e.g. Wikidata, Wikipedia, Unicode, etc...)

Notes:
- The idea is for creating a visual aid to help explain how Scribe projects work together and with external projects.
- Could potentially create two versions - one with the current state of Scribe and the another with the planned architecture - to explain what is currently being worked on and where Scribe is headed.

**Comment by wkyoshida** [comment]
Thinking this could likely most be helpful for first contributors and for presenting Scribe at events.

I could start us off with a simple version, and then we can iterate on it later.

**Comment by andrewtavis** [comment]
Ya this is great, @wkyoshida! Really is a good idea 😊 I think we can just shoot for a full version rather than making one for the WIP state, which isn't to say that the first version wouldn't be simple. Where would you want to make it?

**Comment by wkyoshida** [comment]
> I think we can just shoot for a full version rather than making one for the WIP state, which isn't to say that the first version wouldn't be simple.

Yep - tbf.. the "current" one shouldn't be too difficult once we have the "full" one - mostly just removing couple things :laughing:  

> Where would you want to make it?

Just going for some [mermaid](https://github.com/mermaid-js/mermaid) actually. Pretty simple AND is supported by GitHub markdown (which is sick :rocket:). Example:

The below in markdown..

````
```mermaid
graph LR
    A --->|1. Request| B
    B -.->|2. Action| A & C
```
````

renders into this..

```mermaid
graph LR
    A --->|1. Request| B
    B -.->|2. Action| A & C
```

So, thinking of just putting it in a `.md` file, which will be easy to version control too. I'll create a PR to add the `.md` here in this repo.

**Comment by andrewtavis** [comment]
#9 really is so great, @wkyoshida. Let's present it at the next sync/try it out at the Safari and we can iterate from there :)

**Comment by andrewtavis** [comment]
Should we close this post #9 and #10, @wkyoshida?

**Comment by andrewtavis** [comment]
I guess I'll do it anyway, but let me know if you think that more is needed here and we can re-open :)

**Comment by wkyoshida** [comment]
Yup! Good with closing :wink::+1:
